import type { Metadata } from "next";
import { Google_Sans_Flex } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const googleSansFlex = Google_Sans_Flex({
  variable: "--font-google-sans-flex",
  subsets: ["latin"],
  axes: ["opsz"],
});

const awesomeSerif = localFont({
  variable: "--font-awesome-serif",
  display: "swap",
  src: [
    { path: "./fonts/AwesomeSerif-Var.ttf", style: "normal" },
    { path: "./fonts/AwesomeSerif-Italic-Var.ttf", style: "italic" },
  ],
});

export const metadata: Metadata = {
  title: "Pepti Funnel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${googleSansFlex.variable} ${awesomeSerif.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
